package org.reactome.web.diagram.data.interactors.raw;


import java.util.List;

/**
 * @author Antonio Fabregat <fabregat@ebi.ac.uk>
 */
public interface RawInteractor {

    /**
     * The accession (identifier) for the interactor (e.g. UniProt, ChEBI, etc.)
     */
    String getAcc();

    /**
     * The interactor's gene name for protein or an alternative name for chemical
     */
    String getAlias();

    /**
     * The number of evidences in the server side
     */
    Integer getEvidences();

    /**
     * An autogenerated and autoincremented interaction id
     */
    Long getId();

    /**
     * The score for the current interaction
     */
    double getScore();

    /**
     * (e.g http://www.uniprot.org/uniprot/Q5S007)
     */
    String getAccURL();

    /**
     * (e.g. http://www.ebi.ac.uk/intact/pages/interactions/interactions.xhtml?query=EBI-9029183%20OR%20EBI-9029146%20OR%20EBI-9029639)
     */
    String getEvidencesURL();



    //NEXT methods are not part of the original interface, but are added to ease access to analysis data

    void setIsHit(Boolean isHit);

    Boolean getIsHit();

    void setExp(List<Double> exp);

    List<Double> getExp();

}
